---
- name: PostgreSQL | Copy the RPM repository file
  copy:
    src: pgdg-centos96-9.6-3.noarch.rpm
    dest: /tmp/

- name: PostgreSQL | Install the RPM repository file
  yum:
    name: /tmp/pgdg-centos96-9.6-3.noarch.rpm
    state: present

- name: PostgreSQL | Install packages and dependencies
  yum:
    update_cache: yes
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql96
    - postgresql96-contrib
    - postgresql96-docs
    - postgresql96-plperl
    - postgresql96-plpython
    - postgresql96-server
    - postgresql96-libs
    - python-psycopg2
    - libpqxx-devel
    - acl

- name: PostgreSQL | Initialize the database
  command: /usr/pgsql-9.6/bin/postgresql96-setup initdb
  args:
    creates: /var/lib/pgsql/9.6/data/postgresql.conf

- name: PostgreSQL | Remove listen_addresses line from the configuration file if commented out
  lineinfile:
    dest: "/var/lib/pgsql/9.6/data/postgresql.conf"
    regexp: '^#listen_addresses ='
    state: absent

- name: PostgreSQL | Server daemon will listen in all IP addresses
  lineinfile:
    dest: "/var/lib/pgsql/9.6/data/postgresql.conf"
    line: "listen_addresses = '*'"
    insertafter: "# - Connection Settings -"
    
- name: PostgreSQL | Copy pg_hba.conf file and set permissions
  template:
    src: "{{postgresql_server_pg_hba_file }}"
    dest: "/var/lib/pgsql/9.6/data/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: 0600
  notify: PostgreSQL | Restart (centos)

- name: PostgreSQL | Enable and start server daemon
  service:
    name: postgresql-9.6
    enabled: yes
    state: started
