---
# Install and configure PostgreSQL on CentOS 7
- import_tasks: centos.yml
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == "7"

# Install and configure PostgreSQL on Debian 9
- import_tasks: debian.yml
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version == "9"

# Add users and databases, define privileges
- import_tasks: manage_users_databases.yml
